Greeting.create(greeting: "Hello, World!")
Greeting.create(greeting: "Ciao, Mondo!")
Greeting.create(greeting: "Hola, Mundo!")
Greeting.create(greeting: "Hello, Wêreld!")
Greeting.create(greeting: "Hallo, Welt!")